pipeline {
    agent any
    stages {
       stage("Delete all test-app resources") {
          steps {
             echo "Hello! Pipeline is running! Resources are being deleted!"
             script {
                openshift.withCluster() {
                   openshift.withProject("test-app") { 
		      openshift.selector("all", [ "app" : "test-app" ]).delete() 
     			}   
                    }
                 }  
             }
          }
       stage("Create test-app") {
         steps {
           echo "Creating resources!"
           script {
             openshift.withCluster() {
                openshift.withProject("test-app") {
                  openshift.newApp("s2i-4-toolchain~https://github.com/ritesh97-rh/OC-Test", "--context-dir=s2i/devtoolset/4-toolchain/test/test-app", "--name=test-app") 
                }
            } 
           }
         }
       }
     }
  }
