pipeline {
    agent any
    stages {
       stage("Delete all resources") {
          steps {
             echo "Hello! Pipeline is running!"
             script {
                openshift.withCluster() {
                   openshift.withProject("test-app") { 
		      openshift.selector("all", [app, test-app]).delete() 
     			}   
                    }
                 }  
             }
          }
       }
    }
