pipeline {
    agent any
    stages {
       stage('Delete all resources") {
          steps {
             script {
                openshift.withCluster() {
                   openshift.withProject() {
                      openshift.selector("all", [ template : "test-app" ]).delete() 
                      if (openshift.selector("secrets", "test-app").exists()) { 
                         openshift.selector("secrets", "test-app").delete()
                      }   
                    }
                 }  
             }
          }
       }
    }
}
